### ISSUE TITLE
Install of IoT Edge section uses pre-ga instructions

### ISSUE THREAD

**Issue by toddwhitehead** [Microsoft/MCW-IoT-for-business#13]
The installation process for iot-edge changed significantly between preview and ga and the hol currently still has the pre-ga version

https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20for%20business.md#task-2-install-and-start-the-iot-edge-runtime

**Comment by sebader** [comment]
+1
Instead of manually installing and setting up a VM [here](https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20for%20business.md#task-7-provision-new-linux-virtual-machine-to-run-the-iot-edge-device), simply use the IoT Edge VM in the marketplace: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft_iot_edge.iot_edge_vm_ubuntu

Then it is only one easy setup step to put in your connection string.

**Comment by mrfalafel** [comment]
Yes, this has been updated and a PR has been issued awaiting approval.  
Thanks
